Switch to GHA CI workflow
mezzio/mezzio-skeleton pull request #42
Opened 2021-04-24 12:34 UTC by internalsystemerror

Switch from Travis CI to use GitHub Actions according to: https://gist.github.com/weierophinney/b003e50c3c2667d08076caf31ebd36a4.

This closes #41

2021-04-24 15:43 UTC, internalsystemerror commented
I'm getting different results locally compared to here ... I actually pass CS checks locally since `phpcs.xml` is used whereas here it seems to be using `phpcs.xml.dist` instead (just a hypothesis). And I'm also failing a lot more tests locally, feel free to take over this PR as needed otherwise I'll check back on this later.

2021-04-26 08:57 UTC, brayniverse requested changes

2021-04-26 08:57 UTC, brayniverse commented on test/MezzioInstallerTest/HomePageResponseTest.php
> +                foreach ($this->installTypes as $intallType) {
You could correct the `$intallType` typos here while you're fixing `$this->intallType`.

```suggestion
                foreach ($this->installTypes as $installType) {
```

2021-04-26 08:57 UTC, brayniverse commented on test/MezzioInstallerTest/HomePageResponseTest.php
> +                foreach ($this->installTypes as $intallType) {
```suggestion
                foreach ($this->installTypes as $installType) {
```

The typo is here as well.

2021-05-10 18:54 UTC, internalsystemerror commented
I believe this is now ready for review

2021-05-10 22:01 UTC, merged